import './globals.css';

import Header from '@/components/molecultes/Header';
import Footer from '@/components/molecultes/Footer';
import ThemeRegistry from '@/providers/ThemeRegistry';

import type { Metadata } from 'next';

import { Manrope } from 'next/font/google';
import { QuantumStoreProvider } from '@/providers/QuantumStoreProvider';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Quantum Robotics',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <ThemeRegistry>
          <QuantumStoreProvider>
            <Header />
            <main className="pt-16">{children}</main>
            <Footer />
          </QuantumStoreProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
