import './globals.css';

import Header from '@/components/molecultes/Header';
import Footer from '@/components/molecultes/Footer';
import ApolloClientProvider from "@/components/ApolloClientProvider"
import { QuantumStoreProvider } from '@/providers/QuantumStoreProvider';

import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Quantum Robotics',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ApolloClientProvider>
          <QuantumStoreProvider>
            <Header />
            <main className="pt-16">{children}</main>
            <Footer />
          </QuantumStoreProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
